apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 namespace: default
spec:
 replicas: 2
 selector:
 matchLabels:
 app: nginx-deployment
 template:
 metadata:
 labels:
 spec:
 containers:
 - name: nginx-deploy
 image: nginx
